on:
  release:
    types:
      - published

name: Release

jobs:

  sdist:
    name: Creating source release & pure wheel

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Publishing
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish --build

  build_documentation:
      name: Building & uploading documentation.
      needs: [upload_all]
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Installing Package
        run: poetry install --no-interaction -E celery

      - name: Installing extras
        run: |
            pip install ghp-import

      - name: Building documentation
        run: |
          cd docs && make clean && make html

      - name: Publishing documentation
        run: |
          ghp-import -f -n -p docs/_build/html